---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: demo-policy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-policy
      type: deployment
  template:
    metadata:
      labels:
        app: demo-policy
        type: deployment
    spec:
      containers:
        - name: demo-policy
          image: "ikolomiyets/demo-policy"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080

