---
kind: Service
apiVersion: v1
metadata:
  namespace: kube-demo
  name: demo-policy
spec:
  selector:
    app: demo-policy
    type: deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort

